### ISSUE TITLE
Can it use jagsUI (>= 1.3.1)?

### ISSUE THREAD

**Issue by benmarwick** [mikemeredith/BEST#3]
Hi Mike,

I see you recently added jagsUI (>= 1.3.6), which [broke my build](https://circleci.com/gh/benmarwick/Pleistocene-aged-stone-artefacts-from-Jerimalai--East-Timor/35) because only [1.3.1 is on CRAN](http://cran.r-project.org/web/packages/jagsUI/index.html).

Do you know if the CRAN version of jagsUI will be updated soon? Or perhaps I should just use the github version of that too.

Thanks,  Ben

**Comment by mikemeredith** [comment]
Hi Ben,

Sorry for the inconvenience! I treat the Github version as a devel version, though I do run checks before pushing changes, so all should work. The CRAN version, 0.2.2, uses rjags and should be fine.

jagsUI is a good package and makes it easy to run chains in parallel and simplies the verbose option. But versions prior to 1.3.6 had a serious bug (it called closeAllConnections) which, inter alia, prevented vignettes from compiling. Latest version, 1.3.7, is on Github and is fine. Not sure when Ken will push to CRAN, but the CRANification of a new version of BEST will be delayed until he does! So, yes, in the meantime use the Github version of jagsUI -- or older versions of BEST.

Thanks,  Mike

**Comment by benmarwick** [comment]
Thanks for your very quick reply. My current option is either a debian package or github version. I can't see BEST in the debian repo of R packges (`apt-cache search "^r-cran-b"`), so I'll go with the github version of jagsUI for now. An easy workaround. Thanks again for confirming!

Ben
